dimigoin/dimigoin-back-v3

- src/controllers/meal.ts
- src/models/index.ts
- src/models/meal.ts
- src/resources/date.ts
- src/routes/index.ts
- src/routes/meal.ts
- [GET] /meal - 등록되어 있는 모든 급식 정보 조회
Response
```
{
"meals": [
{
"breakfast": [
"열무김치"
],
"lunch": [
"총각김치"
],
"dinner": [
"오이김치"
],
"_id": "5f410b83422b465321b10e35",
"date": "2020-01-01T00:00:00.000Z",
"__v": 0
},
{
"breakfast": [
"깍두기"
],
"lunch": [
"배추김치"
],
"dinner": [
"갓김치"
],
"_id": "5f4110c3e5354de6c4e99fba",
"date": "2020-01-02T00:00:00.000Z",
"__v": 0
}
]
}
```
- [GET] /meal/yyyy-mm-dd - 특정 날짜 급식 정보 조회
Response
```
{
"meal": {
"breakfast": [
"열무김치"
],
"lunch": [
"총각김치"
],
"dinner": [
"오이김치"
],
"_id": "5f410b83422b465321b10e35",
"date": "2020-01-01T00:00:00.000Z",
"__v": 0
}
}
```
- [PATCH] /meal/yyyy-mm-dd - 급식 수정
Payload
```
{
"breakfast": [
"그냥김치"
],
"lunch": [
"총각김치"
],
"dinner": [
"오이김치"
]
}
```
Response
```
{
"meal": {
"breakfast": [
"그냥김치"
],
"lunch": [
"총각김치"
],
"dinner": …
```
> feat: meal service

- src/models/attendance-log.ts
- src/models/ingang-application.ts
- src/models/meal.ts
- src/models/outgo-request.ts
- src/models/timetable.ts
- src/resources/date.ts
- src/resources/timetable.ts
- src/services/attendance/controllers.ts
- src/services/ingang-application/controllers.ts
- src/services/ingang-application/index.ts
- src/services/meal/controllers.ts
- src/services/meal/index.ts
- src/services/timetable/controllers.ts
Moment 라이브러리 사용, String 기반 데이트, KST 타임존 설정
> refactor: date-related resource

- src/services/ingang-application/controllers.ts
프로퍼티명이 맞지 않아서 인강실 문서를 찾지 못하던 이슈 수정
> fix : modify 'today' property to 'date'

- package.json
- src/models/ingang-application.ts
- src/resources/date.ts
- src/resources/exporter.ts
- src/resources/ingang.ts
- src/services/ingang-application/controllers.ts
- src/services/ingang-application/index.ts
- yarn.lock
> feat: export ingang applications by excel

- src/services/meal/controllers.ts
- src/services/meal/index.ts
`/meal/date/today` 보다는 `/meal/today`가 `/meal/weekly`랑도 통일되고 편할 것 같아서 추가했는데 괜찮으면 머지 해주세요!
> /meal/today 엔드포인트 추가

- src/config.ts
- src/resources/cron.ts
- src/resources/notifier.ts
- src/services/etc/controllers.ts
- src/services/etc/index.ts
- src/services/user/controllers.ts
- src/services/user/index.ts
> feat: add some cron jobs

- .eslintrc.js
- package.json
- src/exceptions/index.ts
- src/index.ts
- src/middlewares/error-handler.ts
- src/resources/cron.ts
- src/resources/logger.ts
- yarn.lock
> feat: implement logging resource

- src/interfaces/dimi-api.ts
- src/models/user.ts
- src/resources/cron.ts
- src/resources/dimi-api.ts
> feat: attach teacher info in user model

- src/services/notice/controllers.ts
- src/services/notice/index.ts
> feat : add remove notice controller

- src/interfaces/user.ts
- src/middlewares/check-permission.ts
- src/models/user.ts
- src/resources/dimi-api.ts
- src/services/afterschool-application/index.ts
- src/services/afterschool/index.ts
- src/services/attendance/index.ts
- src/services/auth/index.ts
- src/services/circle-application-management/index.ts
- src/services/circle-application/index.ts
- src/services/circle-applier-selection/index.ts
- src/services/circle/index.ts
- src/services/config/index.ts
- src/services/etc/index.ts
- src/services/fcm/index.ts
- src/services/file/index.ts
- src/services/index.ts
- src/services/ingang-application/index.ts
- src/services/meal/index.ts
- src/services/notice/index.ts
- src/services/outgo-management/index.ts
- src/services/outgo-request/index.ts
- src/services/place/index.ts
- src/services/timetable/index.ts
- src/services/user/index.ts
단순 유저 타입 체크 기반의 권한 시스템에서 서비스별 권한 시스템으로 개선합니다.
> feat: implement new permission system

- src/services/attendance/controllers.ts
- src/services/attendance/index.ts
> feat: implement class attendance timeline endpoint

- src/services/ingang-application/controllers.ts
- src/services/ingang-application/index.ts
관리자 및 인강실 도우미를 위한 오늘 생성된 전체 인강실 신청을 불러오는 엔드포인트를 추가합니다.
> feat: implement getting entire ingang applications endpoint

- src/express.d.ts
- src/interfaces/afterschool-application.ts
- src/interfaces/afterschool.ts
- src/interfaces/dimi-api.ts
- src/interfaces/index.ts
- src/interfaces/ingang-application.ts
- src/interfaces/place.ts
- src/interfaces/user.ts
- src/resources/dimi-api.ts
- src/resources/exporter/afterschool-application.ts
- src/resources/file.ts
- src/resources/token.ts
- src/services/auth/controllers.ts
- src/services/index.ts
> refactor: add missing interfaces

- src/services/ingang-application/controllers.ts
- src/services/ingang-application/index.ts
인강실 관리자가 오늘 인강실을 신청한 학생을 인강실로 강제 출석시키는 엔드포인트를 추가합니다.
> feat: implement forceApplierToAttendnaceIngangsil endpoint

- src/models/index.ts
- src/models/mentoring.ts
- src/resources/default.ts
- src/services/mentoring/controllers.ts
- src/services/mentoring/index.ts
- src/types/index.ts
> feat: mentoring service

- src/models/index.ts
- src/models/mentoring-application.ts
- src/models/mentoring.ts
- src/resources/date.ts
- src/services/mentoring-application/controllers.ts
- src/services/mentoring-application/index.ts
- src/services/mentoring/controllers.ts
- src/services/mentoring/index.ts
- src/types/index.ts
멘토링 수강 신청 서비스를 추가합니다.
신청 가능한 멘토링 수업을 신청 여부와 함께 반환하는 엔드포인트를 추가합니다.
> feat: implement mentoring application service

- .eslintrc.js
- src/models/circle.ts
- src/services/circle-application-management/controllers.ts
- src/services/circle-application-management/index.ts
- src/services/circle-application/controllers.ts
- src/services/circle-application/index.ts
- src/services/circle-applier-selection/controllers.ts
- src/services/circle-applier-selection/index.ts
- src/services/circle/controllers.ts
- src/services/circle/index.ts
동아리 관련 서비스 관련 오류를 수정하고 리팩터링 합니다.
> refactor: circle-related services

- src/services/attendance/controllers.ts
학생별 히스토리 컨트롤러에서 `updateBy` 필드를 populate해서 반환합니다
> feat : getStudentAttendanceHistory populate updateBy

- src/interfaces/dimi-api.ts
- src/models/user.ts
- src/resources/dimi-api.ts
- src/resources/model-validators.ts
- src/services/auth/controllers.ts
디미고 API에서 사용자들의 생년월일 정보를 불러옵니다.
> feat: add birthday field in user model

- src/models/notice.ts
- src/services/notice/controllers.ts
> feat: add author field in notice model

- src/interfaces/dimi-api.ts
- src/interfaces/user.ts
- src/models/user.ts
- src/resources/dimi-api.ts
- src/services/auth/controllers.ts
> feat: add libraryId field in user model

- src/middlewares/check-period.ts
- src/resources/default.ts
- src/services/afterschool-application/index.ts
- src/services/ingang-application/controllers.ts
- src/services/ingang-application/index.ts
- src/types/index.ts
방과 후 수강 신청 기간을 확인합니다.
인강실 신청 기간 확인을 미들웨어에서 처리합니다.
> feat: check afterschool apply period in middlware

- src/resources/dimi-api.ts
- src/services/auth/controllers.ts
> feat: implement chairman permission

- src/services/circle-application/controllers.ts
- src/services/circle-application/index.ts
자신의 동아리에 지원한 학생이 함께 지원한 동아리 목록을 반환해 주는 엔드포인트를 추가합니다.
> feat: implement getApplicationsByApplier endpoint

- src/models/dets-application.ts
- src/models/dets.ts
- src/models/index.ts
- src/services/dets/controllers.ts
- src/services/dets/index.ts
> feat: implement dets service

- src/models/dets.ts
- src/services/dets-application/controllers.ts
- src/services/dets-application/index.ts
> feat: implement dets-application service

- .eslintrc.js
- src/models/circle.ts
- src/services/circle/controllers.ts
- src/services/circle/index.ts
- src/types/index.ts
@rycont 요청으로,
CirclePeriod에 SUBMITTING / REGISTERING 추가 및 circle 모델에 Description 필드에서 required 를 제거하였습니다.
> CirclePeriod에 SUBMITTING / REGISTERING 추가 

- src/models/circle.ts
- src/resources/default.ts
- src/types/index.ts
동아리 신청시 사용하는 카테고리를 지정된 타입에서 자유입력으로 변경합니다
> fix: remove category enum & validation

- src/models/circle.ts
- src/services/circle/index.ts
@rycont 요청으로 작업했습니다.
동아리 모델에 fullName을 required : false 로 추가하였습니다.
또한 editCircle , createCircle 에 해당하는 라우터 validation에 fullName을 추가하였습니다.
> fix: add fullName for circle model & router validation

- src/services/circle/controllers.ts
@rycont application 상태가 아닐때 수정을 막습니다.
> fix: block edit at application period - 2

- src/types/index.ts
> fix: add screening period

- src/services/mentoring-application/controllers.ts
현 해당 검증 로직때문에 신청이 안되고 있다고 합니다.
임시로 주석 처리해두고 추후 제가 수정하겠습니다 :D
> fix: remove mentoring days validation logic at application

- src/models/meal.ts
- src/services/meal/index.ts
> feat: add meal image property in meal model

- src/resources/dalgeurak.ts
- src/services/dalgeurak-management/controllers.ts
- src/services/dalgeurak-management/index.ts
- src/services/dalgeurak/controllers.ts
- src/services/dalgeurak/index.ts
- src/types/index.ts
선/후밥 여부
급식 시간 체크
디넌장 전용 서비스 추가
- 디넌 권한 부여
- 디넌 권한 삭제
- 디넌장 위임
> feat: Added the func of bring in information

- src/services/dalgeurak/index.ts
> feat: removed dalgeurak checkin dienen permission

- src/firebase-config.ts
- src/models/dalgeurak/checkinlog.ts
- src/models/dalgeurak/mealexception.ts
- src/models/dalgeurak/warning.ts
- src/models/user.ts
- src/resources/dalgeurakPush.ts
- src/services/dalgeurak-management/controllers.ts
- src/services/dalgeurak-management/index.ts
- src/services/dalgeurak/controllers.ts
- src/services/dalgeurak/index.ts
> feat: lookup checkinlog func AND set warning func

- src/services/dalgeurak/controllers.ts
설명 요약 :
급식 지연시간을 설정 할 때 현재 배식 중인 반의 다음 순서 반 부터 모두 지연알림을 보내는 로직
> feat: set push message targetting when setting extra minute

- package.json
- src/app.ts
- src/config.ts
- src/resources/socket.ts
- yarn.lock
> test: socket test code

- src/middlewares/check-application-time.ts
- src/models/dalgeurak/mealexception.ts
- src/models/dalgeurak/mealorder.ts
- src/models/user.ts
- src/resources/cron.ts
- src/resources/dalgeurak.ts
- src/resources/date.ts
- src/resources/default/index.ts
- src/services/auth/controllers.ts
- src/services/dalgeurak/controllers.ts
- src/services/dalgeurak/index.ts
- src/types/index.ts
> feat: first meal ticket

- src/middlewares/check-permission.ts
- src/services/auth/controllers.ts
- src/services/dalgeurak/controllers.ts
- src/services/dalgeurak/index.ts
- src/services/index.ts
임시로그인에서 기존 디미고 api 로그인 방식으로 바꿨습니다.
> fix: change the authentication method

- .github/workflows/deploy.yml
- package.json
- src/services/auth/controllers.ts
- yarn.lock
api.dimigo.hs.kr 서버가 죽었기에 테스트를 위해 다시 임시비밀번호로 되돌립니다.
> revert temporary login

- src/middlewares/check-permission.ts
- src/services/afterschool-application/controllers.ts
- src/services/dalgeurak/index.ts
https://github.com/dimigoin/dimigoin-back-v3/issues/141#issue-1341435029
https://github.com/dimigoin/dimigoin-back-v3/issues/142#issue-1341455184
https://github.com/dimigoin/dimigoin-back-v3/issues/143#issue-1341465741
> 교사 권한 버그 수정

- src/models/dalgeurak/convenience-checkin.ts
- src/models/dalgeurak/convenience-deprive.ts
- src/models/dalgeurak/convenience-food.ts
- src/services/dalgeurak/warning.controller.ts
https://github.com/dimigoin/dimigoin-back-v3/issues/147#issue-1343282373
> 달그락 경고 불러오기 API(GET /dalgeurak/warning) 응답 형식 오류 해결

- src/models/dalgeurak/index.ts
- src/models/dalgeurak/mealconfig.ts
- src/models/dalgeurak/mealorder.ts
- src/resources/dalgeurak.ts
- src/services/dalgeurak/config.controller.ts
- src/services/dalgeurak/dinnen.controller.ts
- src/services/dalgeurak/extra.controller.ts
- src/services/dalgeurak/index.ts
- src/types/index.ts
잔류 급식 가격
가격 수정 : https://imminent-fortnight-5dc.notion.site/9642f1e8ac944c0fa527af384f629afd
가격 불러오기 :  https://imminent-fortnight-5dc.notion.site/83b3154edb184bc59e3a810643a286e5
> 잔류 급식 가격 변경 endpoint

- src/services/afterschool/index.ts
2023년부터 야자1타임에도 방과후 프로그램 진행햔다 하여 관련 schema 수정했습니다
> chore: edit afterschool times

- package.json
- yarn.lock
Reverts dimigoin/dimigoin-back-v3#236
> Revert "chore(deps): bump mongoose from 5.9.27 to 5.13.15"

- src/interfaces/washer.ts
- src/models/index.ts
- src/models/washer.ts
- src/services/laundry/controllers.ts
- src/services/laundry/index.ts
- src/types/index.ts
Developing laundry service ( not finished )
> test: Developing laundry service

- src/interfaces/index.ts
- src/interfaces/washer.ts
- src/models/frigo.ts
- src/models/index.ts
- src/models/washer.ts
- src/services/frigo/controllers.ts
- src/services/frigo/index.ts
- src/services/laundry/controllers.ts
- src/services/laundry/index.ts
- src/types/index.ts
> Feat: Frigo, Laundry

- src/interfaces/index.ts
- src/interfaces/outgo.ts
- src/interfaces/stay.ts
- src/models/index.ts
- src/models/stay-application.ts
- src/models/stay-outgo.ts
- src/models/stay.ts
- src/resources/outgo.ts
- src/services/laundry/controllers.ts
- src/services/outgo-management/controllers.ts
- src/services/outgo-management/index.ts
- src/services/outgo-request/controllers.ts
- src/services/outgo-request/index.ts
- src/services/stay-outgo/controllers.ts
- src/services/stay-outgo/index.ts
- src/services/stay/controllers.ts
- src/services/stay/index.ts
- src/types/index.ts
feat: stay, stayOutgo, Outgo, fix: etc.
> feat: stay, stayOutgo, Outgo
